#! /bin/bash
call(){
    
}

adbInitServer(){
    $RUNMSG ">> Starting ADB Server..."
    # restart adb server
    checkRun "sudo adb kill-server"
    checkRun "sudo adb start-server"
    _RetVal[0]=0
}

adbInitDevice(){
    temp=(`checkRun "adb devices"`)
    deviceID=${temp[4]}
    $WARNT "-- Set Device ID to: $deviceid"
    adbshell="adb -s $deviceID shell "
    adbGetScreenSize
    screenX=_RetVal[0]
    screenY=_RetVal[1] 
    $WARNT "-- Set Device's Screen Size to: $screenX x $screenY"
    _RetVal[0]=$deviceID
}

adbGetScreenSize(){
    if [ ${screenX}x != x ]
    then 
        call getScreenSize
        _RetVal[0]=${screen[0]}
        _RetVal[1]=${screen[1]}
    else 
        _RetVal[0]=$screenX
        _RetVal[1]=$screenY
    fi
}
